name: Publish

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: echo $AGENT_TOOLSDIRECTORY
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: python -m pip install --upgrade pyyaml
      - name: Gen Build Command
        run: |
          export BUILD_COMMAND=$((python ./conda.recipes/getChannels.py) 2>&1)
          echo "::set-env name=BUILD_COMMAND::$BUILD_COMMAND"
      - name: publish-to-conda
        uses: rfun/conda-package-publish-action@master
        with:
          subDir: "conda.recipes"
          AnacondaToken: ${{ secrets.ANACONDA_TOKEN }}
